version: '3'

services:
  mongo1:
    container_name: mongo1
    image: mongo:5
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo1
    ports:
      - "27017:27017"
    networks:
      - mongoCluster

  mongo2:
    container_name: mongo2
    image: mongo:5
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo2
    ports:
      - "27018:27017"
    networks:
      - mongoCluster

  mongo3:
    container_name: mongo3
    image: mongo:5
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo3
    ports:
      - "27019:27017"
    networks:
      - mongoCluster

networks:
  mongoCluster:
    external: true
